# kubetpl:syntax:$

apiVersion: v1
data:
  robots.txt: |
    User-agent: *
    Disallow: /
kind: ConfigMap
kubetpl/data-from-file:
- index.html
- 404.html=index.html
metadata:
  name: $NAME
---
apiVesion: v1
kind: Secret
metadata:
  name: $NAME-ingress-secret
type: Opaque
kubetpl/data-from-file:
- tls.key
- tls.crt
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: $NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: $NAME
    spec:
      containers:
      - image: nginx:1.7.9
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: $NAME-volume
          mountPath: /usr/share/nginx/html
        envFrom:
        - configMapRef:
            name: $NAME
        env:
        - name: ROBOTS_TXT
          valueFrom:
            configMapKeyRef:
              name: $NAME
              key: robots.txt
      volumes:
      - configMap:
          name: $NAME
        name: $NAME-volume
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $NAME-ingress
spec:
  tls:
  - hosts:
    - sslexample.foo.com
    secretName: $NAME-ingress-secret
  rules:
    - host: sslexample.foo.com
      http:
        paths:
        - path: /
          backend:
            serviceName: service1
            servicePort: 80
